### ISSUE TITLE
How does this work?! 

### ISSUE THREAD

**Issue by Regista6** [ThomasSteere/AI-SBC#1]
Hello,

This looks amazing especially because I think you have automated the entire input process of solving a sbc.

Can you give an overview of how this works? 

Btw, I added a [commit ](https://github.com/Regista6/EA-FC-24-Automated-SBC-Solving/commit/ae37657a9e56c1cf62d2e56d14e7c6269a4108c4)few days back, could be of use to you.

Please do consider reaching out to me (Discord: watchdogs132#8237) if you have any questions or suggestions! 

Thank you 🙏

**Comment by ThomasSteere** [comment]
Hi, basically I saw your post on reddit about automating sbcs. I have been playing around in the front end of the webapp a bit so i can basically manipulate it however i want and added your bit in as a backend interfaced via api using the data straight from the app. A few changes to make your bit work with mine and it now cranks out most sbcs automatically. ( i did find a few things to that need a bit of a tune up ).  I'll get a login to discord and hit you up when I'm back from holiday to have a chat.
