### ISSUE TITLE
Feedbacks, Multiple rarity considering, No priced players

### ISSUE THREAD

**Issue by GeekFiro** [ThomasSteere/AI-SBC#2]
Hi man! 

Firstly, it is a really great work! Thank you for that!
I already use Regista6's solution every day and I really appreciate for it! I always wanted something would be really good if it could work with the frontend.
I know there are some paid services for it but it would be really good to have an open source solution for it, especially for developers like us.
I have some feedbacks for the repository and I think after that everyone can use it easily.

I ran it successfully, but it would be really good to have some installment and using instructions in order on Readme file. (Like installing tampermonkey and import script and there is not anything about Solve SBC button on there, so people maybe confuse how to use that tool)

- The first thing I noticed when I tried, when we have two rarity requirements it only accepts one. I added a screenshot for it. It only considers Rare Min 5 players requirements and not consider Gold 10 players requirement.

<img width="600" alt="image" src="https://github.com/ThomasSteere/AI-SBC/assets/155772699/04d60a55-d28a-442d-b35f-a68a3554d083">

- And the second thing, it adds objective players (players who have 0 price) to the solutions. Regista6 ignored them in python solutions maybe you can also consider to eliminate 0 price players too.

These are my first impressions and feedbacks. I know they can be solved easily and again thank you for all of that man! 
And also you can add me (geekfiro) on Discord too for further discussions. 

It is really good solution and please keep that good work up!

**Comment by ThomasSteere** [comment]
Check out latest commits that addresses this feedback
